apply gitlabci-lint --fix
benthosdev/benthos pull request #1461
Opened 2022-09-24 19:21 UTC by peczenyj

most of the changes are cosmetic

2022-09-26 10:51 UTC, mihaitodor reviewed
Thanks for looking into this! When I started the initial effort to bring in some linters, I tried to avoid the ones which seemed overly-restrictive, so it won't feel too nitpicky at first. Also, do these extra linters increase the golangci-lint run time much?

2022-09-26 11:42 UTC, peczenyj commented on internal/docs/yaml_test.go
> -  eles:
oh it seems the linter misspell that thinkgs that the term `eles` was about `eels`

we can revert this specific file if you want, or substitute by something that have no meaning like 'lol'

2022-09-26 11:45 UTC, mihaitodor commented on internal/docs/yaml_test.go
> -  eles:
It's more of a generic concern that the linter which caused this change might be annoying in other similar situations in the future. If it's just one place, then yeah, maybe change it to `bar` or smth like that.

2022-09-26 11:45 UTC, peczenyj commented
> Thanks for looking into this! When I started the initial effort to bring in some linters, I tried to avoid the ones which seemed overly-restrictive, so it won't feel too nitpicky at first. Also, do these extra linters increase the golangci-lint run time much?

@mihaitodor I did not update the list of linters, I am just telling what was the list used to apply the automatic fixes via option `--fix`

I do not recomment enable the entire list because it will be insane to review and fix (and most of them does not add a real value, only keeps the code more readable like lll that avoids long lines).

this can be done step by step if needed

2022-09-26 11:46 UTC, mihaitodor commented
OK, but then the changes from this PR won't be enforced in the future via GitHub Actions, or I'm not sure I follow.

2022-09-26 12:02 UTC, peczenyj commented
> OK, but then the changes from this PR won't be enforced in the future via GitHub Actions, or I'm not sure I follow.

No they will not enforced

2022-09-26 19:41 UTC, Jeffail requested changes
LGTM, some of the comments look a bit odd ending with a period but I don't mind swallowing the whole pill for the sake of the spelling corrections, which there are surprisingly many 😅

Just one suggestion, obviously an unfinished comment so might as well trim the whole second bit.

2022-09-26 19:41 UTC, Jeffail commented on public/service/processor.go
> +// Close the processor, allowing it to clean up resources. It is.
```suggestion
// Close the processor, allowing it to clean up resources.
```

2022-09-27 07:57 UTC, peczenyj commented
done

2022-09-29 19:40 UTC, Jeffail approved these changes

2022-09-29 19:40 UTC, Jeffail commented
Thanks @peczenyj! I officially declare this repo typo and spelling error free... FOREVER.

2022-09-29 19:41 UTC, merged